device: 'cpu'
log_path: './log.txt'
data:
  vocab_path: './data/vocab_txts/uk-short_splits.txt'
  frequency_sampling: false
  min_word_length: 3
  max_word_length: 10
model:
  embedding:
    embedding_dim: 64
  gru:
    input_size: 64
    hidden_size: 256
    num_layers: 5
    batch_first: true
train:
  optim:
  lr: 0.0001
  epochs: 1
  batch_size: 256
generate:
  max_len: 256
  temperature: 1.0
eval:
  prefix_length: 2
  num_prefixes: 5
  n_trials: 10
wandb:
  project: 'nonce_lstm'
